### ISSUE TITLE
Add git-leaks config

### ISSUE THREAD

**Issue by kevcube** [trunk-io/configs#8]
add .gitleaks.toml file to this repo please.

Currently I'm unsure where I should place it.

`$REPO_ROOT/.gitleaks.toml` and `$REPO_ROOT/gitleaks.toml` both seem to be not recognized by trunk for me.

**Comment by dapirian** [comment]
Hi 👋  - Sorry about that, it looks like we were only respecting `.gitleaks.config`. Did gitleaks change it's config naming recently? Either way, it's a simple config change and I'll update it for the next release (you can also override this in `trunk.yaml` to get the behavior in the meantime).

For adding a `.gitleaks.toml` to this repo, what would you suggest? It seems like the default is pretty good (generally no configuration is needed?).

**Comment by kevcube** [comment]
@dapirian yeah the default is pretty good. I'm still familiarizing myself with their config language but it'd be nice to have some inline-ignore functionality. Currently I have to set an allow regex to ignore AWS keys with the text `EXAMPLE` in them, and to ignore any lines ending in `#nosec` or `//nosec` based on https://github.com/zricethezav/gitleaks/issues/579

Any advice on how to set this in `trunk.yaml`?

Mine looks like ..

```yaml
version: 0.1
cli:
  version: 0.8.1-beta
lint:
  enabled:
    - actionlint@1.6.9
    - gitleaks@8.3.0
    - hadolint@2.8.0
    - markdownlint@0.31.1
    - prettier@2.5.1
    - shellcheck@0.8.0
    - shfmt@3.4.0
environments:
  - name: gitleaks
    environment:
      - name: GITLEAKS_CONFIG
        value: .gitleaks.toml
```
but it doesn't appear to be picked up. My `gitleaks.toml` is at the repo root.
